CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

NAME = Zombie
SRCS =	main.cpp \
		newZombie.cpp \
		randomChump.cpp 

OBJS = $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all